### PR TITLE
Add swagger dependency

### PR DESCRIPTION
**Pull request by Szachista**
I couldn't launch project, therefore I added _exclude = {DataSourceAutoConfiguration.class }_ parameter in the _SpringBootApplication_ annotation.

### CODE REVIEW

**Comment by MaciejJ0** [comment]
It is probably better to use swagger 3
https://www.baeldung.com/spring-rest-openapi-documentation

**Comment by patrykzawadzkiintive** [comment]
Good point! Please use swagger 3 :) from @MaciejJ0 link. Maybe exclusion will be not required then?

**Comment by Szachista** [comment]
> Good point! Please use swagger 3 :) from @MaciejJ0 link. Maybe exclusion will be not required then?

Done. Without exclusion I get error:
image

**Review by MaciejJ0 — APPROVED** [review]

**Review by MaciejJ0 — APPROVED** [review]

**Comment by patrykzawadzkiintive** [comment]
@Szachista ok i found why you need to exclude = {DataSourceAutoConfiguration.class }. **Please remove that and rebase the project on newest master.** Then everythin will be ok.

 I have commited fix for that. The reason was spring-boot-starter-data-jpa in pom.xml. It requires initial configuration for database which was not provided yet. I commented temporary this dependency.

**Comment by Szachista** [comment]
Exclusion removed.

**Review by edych — APPROVED** [review]

**Review by patrykzawadzkiintive — APPROVED** [review]

**Review by golldfish — APPROVED** [review]

**Review by Radenzvous — APPROVED** [review]

**Pull request merged**
